### ISSUE TITLE
Can we display a tooltip on mouse hover of a node

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [BasicPrimitives/react-demo#52]
I want to display a tooltip on mouse hover of each node. I see there is an onHighlightChanged event.When I hover a node I am getting the details of that node.But I am not able to set tooltip inside that event.Can you please let me know if there is a way in basicpremitive to display tooltip on mouse hover of a node?

**Comment by BasicPrimitives** [comment]
1. Disable highlight, set navigationMode = NavigationMode.CursorOnly
- Callout annotation and Keyboard navigation don't work without highlight
2. Modify item template to add Tooltip of your choice
https://www.basicprimitives.com/reactusecases/itemtemplates
